{% set version = '0.2.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pedquant
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pedquant_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pedquant/pedquant_{{ version }}.tar.gz
  sha256: 663262b255a3aa80b97a70f2685ce7e0153710ed827f333feba867eeb54de24d

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-performanceanalytics
    - r-ttr
    - r-curl
    - r-data.table
    - r-echarts4r
    - r-httr
    - r-jsonlite
    - r-lubridate
    - r-readr
    - r-readxl
    - r-rvest
    - r-stringi
    - r-xefun
    - r-zoo
  run:
    - r-base
    - r-performanceanalytics
    - r-ttr
    - r-curl
    - r-data.table
    - r-echarts4r
    - r-httr
    - r-jsonlite
    - r-lubridate
    - r-readr
    - r-readxl
    - r-rvest
    - r-stringi
    - r-xefun
    - r-zoo

test:
  commands:
    - $R -e "library('pedquant')"           # [not win]
    - "\"%R%\" -e \"library('pedquant')\""  # [win]

about:
  home: https://github.com/ShichenXie/pedquant
  license: GPL-3.0-only
  summary: Provides an interface to access public economic and financial data for economic research
    and quantitative analysis. The data sources including NBS, FRED, 163, Sina, Eastmoney
    and etc. It also provides quantitative functions for trading strategies based on
    the 'data.table', 'TTR', 'PerformanceAnalytics' and etc packages.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - l2dy

# Package: pedquant
# Version: 0.2.1
# Title: Public Economic Data and Quantitative Analysis
# Description: Provides an interface to access public economic and financial data for economic research and quantitative analysis. The data sources including NBS, FRED, 163, Sina, Eastmoney and etc. It also provides quantitative functions for trading strategies based on the 'data.table', 'TTR', 'PerformanceAnalytics' and etc packages.
# Authors@R: person("Shichen", "Xie", email = "xie@shichen.name", role = c("aut", "cre"))
# Depends: R (>= 4.1.0)
# Imports: data.table, TTR, zoo, PerformanceAnalytics, curl, httr, rvest, lubridate, stringi, jsonlite, readxl, readr, echarts4r, xefun
# Suggests: knitr, rmarkdown
# License: GPL-3
# URL: https://github.com/ShichenXie/pedquant
# BugReports: https://github.com/ShichenXie/pedquant/issues
# LazyData: true
# RoxygenNote: 7.2.1
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2022-11-12 09:50:56 UTC; shichenxie
# Author: Shichen Xie [aut, cre]
# Maintainer: Shichen Xie <xie@shichen.name>
# Repository: CRAN
# Date/Publication: 2022-11-12 10:20:02 UTC
